site_name: klickbrick
repo_url: https://github.com/rnwolf/klickbrick
site_dir: public

markdown_extensions:
  - plantuml_markdown
  - toc:
      anchorlink: True
      separator: "_"
  - admonition
  - tables
  - sane_lists
